author: H31IX
database: false
description: Wraps the minecraft world.
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: net.h31ix.worldwrap.Worldwrap
name: WorldWrap
startup: postworld
url: http://H31IX.NET/
version: '1.0'
